config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, except: [:update, :destroy] do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, :dependent => :destroy
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false,}
  validates :content, presence: true
  validates :rating, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end

  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to task_params
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]


  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end

  end


  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= yield %>
</body>

</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category %>
<%= f.button :submit, class: 'btn btn-danger' %>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<% @restaurants.each do |restaurant| %>
<%= link_to restaurant.name, restaurant_path(restaurant) %>

<%= restaurant.address %>

<%= restaurant.phone_number %>
<%= link_to "Editer #{restaurant.name}", edit_restaurant_path(restaurant) %>

<% end %>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<%= link_to @restaurant.name, restaurant_path(@restaurant) %>

<%= @restaurant.address %>

<%= @restaurant.phone_number %>
<%= link_to "leave a reviews", new_restaurant_review_path(@restaurant) %>
<%= link_to "Editer #{@restaurant.name}", edit_restaurant_path(@restaurant) %>
<% @restaurant.reviews.each do |review| %>
<%= review.content %>
<%= review.rating %>
<% end %>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.button :submit, class: 'btn btn-danger' %>
<% end %>

app/views/reviews/new.html.erb
<% simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.button :submit, class: 'btn btn-danger' %>
<% end %>